// client/app/service/page.tsx
"use client";

import { useState, useEffect } from "react";
import gigworks from "../../public/assets/media/gigworksblk.svg";
import Image from "next/image";
import { fetchBusinessData } from "../api/index";
import { CategorySkeleton } from "../components/categorySkelton";
import ServiceSearchSection from "../components/ServiceSearchSection";
import Router from "next/navigation";

import {
  Home,
  Book,
  PenToolIcon as Tool,
  Briefcase,
  Calendar,
  Heart,
  Cross,
  Hammer,
  Users,
  Truck,
  Car, // <-- Add this line
  Search,
  MessageCircle,
  MapPin,
  Phone,
  Mail,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { FooterSection } from "../components/FooterSection";
import Link from "next/link";

interface Category {
  id: string;
  title: string;
  src: string;
  name?: string;
}

export default function HomePage() {
  const [language, setLanguage] = useState<"en" | "ml">("en");
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const [fetchedCategories, setFetchedCategories] = useState<Category[]>([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(true);

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        setIsLoadingCategories(true);
        const response = await fetchBusinessData({ hasBusiness: true });

        // Format categories from API response
        const validCategories =
          response.data.categories
            ?.map((cat: any) =>
              cat.businessCount !== 0
                ? {
                    id: cat.id || "",
                    title: cat.name || cat.title || "Untitled",
                    src: cat.src || "/icons/default.svg",
                  }
                : null
            )
            .filter((cat: any) => cat !== null) || [];

        setFetchedCategories(validCategories);
      } catch (error) {
        console.error("Error fetching categories:", error);
        setFetchedCategories([]); // Set empty array on error
      } finally {
        setIsLoadingCategories(false);
      }
    };

    fetchCategories();
  }, []);

  const toggleLanguage = () => {
    setLanguage(language === "en" ? "ml" : "en");
  };

  const translations = {
    // Translations based on current language
    heroTitle:
      language === "en"
        ? "Find Trusted Experts Near You"
        : "നിങ്ങൾക്ക് അടുത്തുള്ള വിശ്വസനീയരായ വിദഗ്ധരെ കണ്ടെത്തുക",
    heroSubtitle:
      language === "en"
        ? "Connect with skilled professionals in Kerala via WhatsApp for all your service needs"
        : "നിങ്ങളുടെ എല്ലാ സേവന ആവശ്യങ്ങൾക്കും വാട്സ്ആപ്പ് വഴി കേരളത്തിലെ വിദഗ്ധ പ്രൊഫഷണലുകളുമായി ബന്ധപ്പെടുക",
    searchPlaceholder:
      language === "en" ? "Search for a service..." : "ഒരു സേവനം തിരയുക...",
    whatsappCTA:
      language === "en" ? "Chat on WhatsApp" : "വാട്സ്ആപ്പിൽ ചാറ്റ് ചെയ്യുക",
    categoriesTitle:
      language === "en"
        ? "Browse Services by Category"
        : "വിഭാഗം അനുസരിച്ച് സേവനങ്ങൾ ബ്രൗസ് ചെയ്യുക",
    howItWorksTitle:
      language === "en" ? "How It Works" : "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    testimonialsTitle:
      language === "en"
        ? "What Our Users Say"
        : "ഞങ്ങളുടെ ഉപയോക്താക്കൾ പറയുന്നത്",
    ctaTitle:
      language === "en"
        ? "Ready to Find Your Service Provider?"
        : "നിങ്ങളുടെ സേവന ദാതാവിനെ കണ്ടെത്താൻ തയ്യാറാണോ?",
    ctaSubtitle:
      language === "en"
        ? "Start a conversation on WhatsApp and get connected with the best professionals in Kerala"
        : "വാട്സ്ആപ്പിൽ ഒരു സംഭാഷണം ആരംഭിക്കുകയും കേരളത്തിലെ മികച്ച പ്രൊഫഷണലുകളുമായി ബന്ധപ്പെടുകയും ചെയ്യുക",
    startWhatsapp:
      language === "en" ? "Start on WhatsApp" : "വാട്സ്ആപ്പിൽ ആരംഭിക്കുക",
    footerTagline:
      language === "en"
        ? "Connecting Kerala with trusted local service providers"
        : "കേരളത്തെ വിശ്വസനീയമായ പ്രാദേശിക സേവന ദാതാക്കളുമായി ബന്ധിപ്പിക്കുന്നു",
    quickLinks: language === "en" ? "Quick Links" : "ക്വിക്ക് ലിങ്കുകൾ",
    aboutUs: language === "en" ? "About Us" : "ഞങ്ങളെക്കുറിച്ച്",
    services: language === "en" ? "Services" : "സേവനങ്ങൾ",
    contactUs: language === "en" ? "Contact Us" : "ഞങ്ങളെ സമീപിക്കുക",
    contact: language === "en" ? "Contact" : "ബന്ധപ്പെടുക",
    allRightsReserved:
      language === "en"
        ? "All Rights Reserved"
        : "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം",
    signIn: language === "en" ? "Chat " : "സൈൻ ഇൻ",
  };

  const categories = [
    {
      name: "Home Services",
      nameMl: "ഹോം സർവീസസ്",
      icon: "home",
    },
    {
      name: "Education",
      nameMl: "വിദ്യാഭ്യാസം",
      icon: "book",
    },
    {
      name: "Repairs",
      nameMl: "റിപ്പയറുകൾ",
      icon: "tool",
    },
    {
      name: "Professional",
      nameMl: "പ്രൊഫഷണൽ",
      icon: "briefcase",
    },
    {
      name: "Events",
      nameMl: "ഇവന്റുകൾ",
      icon: "calendar",
    },
    {
      name: "Healthcare",
      nameMl: "ആരോഗ്യ പരിരക്ഷ",
      icon: "heart",
    },
    {
      name: "Beauty",
      nameMl: "സൗന്ദര്യം",
      icon: "users",
    },
    {
      name: "Delivery",
      nameMl: "ഡെലിവറി",
      icon: "truck",
    },
  ];

  const steps = [
    {
      title: "Search or Choose a Category",
      titleMl: "തിരയുക അല്ലെങ്കിൽ ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക",
      description:
        "Find the service you need from our wide range of categories",
      descriptionMl:
        "ഞങ്ങളുടെ വിപുലമായ വിഭാഗങ്ങളിൽ നിന്ന് നിങ്ങൾക്ക് ആവശ്യമായ സേവനം കണ്ടെത്തുക",
      icon: "search",
    },
    {
      title: "Chat on WhatsApp",
      titleMl: "വാട്സ്ആപ്പിൽ ചാറ്റ് ചെയ്യുക",
      description: "Connect directly with service providers via WhatsApp",
      descriptionMl: "വാട്സ്ആപ്പ് വഴി സേവന ദാതാക്കളുമായി നേരിട്ട് ബന്ധപ്പെടുക",
      icon: "message",
    },
    {
      title: "Get the Service",
      titleMl: "സേവനം നേടുക",
      description: "Receive quality service from trusted local professionals",
      descriptionMl:
        "വിശ്വസനീയമായ പ്രാദേശിക പ്രൊഫഷണലുകളിൽ നിന്ന് ഗുണനിലവാരമുള്ള സേവനം ലഭിക്കുക",
      icon: "users",
    },
  ];

  const testimonials = [
    {
      name: "Priya Thomas",
      location: "Kochi",
      text: "Found an excellent electrician through Gigwork. He fixed all the issues in my new apartment within hours. The WhatsApp connection made it so easy!",
      textMl:
        "ഗിഗ്‌വർക്ക് വഴി ഒരു മികച്ച ഇലക്ട്രീഷ്യനെ കണ്ടെത്തി. എന്റെ പുതിയ അപ്പാർട്ട്മെന്റിലെ എല്ലാ പ്രശ്നങ്ങളും അദ്ദേഹം മണിക്കൂറുകൾക്കുള്ളിൽ പരിഹരിച്ചു. വാട്സ്ആപ്പ് കണക്ഷൻ അത് വളരെ എളുപ്പമാക്കി!",
      rating: 5,
    },
    {
      name: "Rahul Menon",
      location: "Trivandrum",
      text: "Needed a math tutor for my daughter urgently. Gigwork connected me with a qualified teacher in my neighborhood within minutes. Highly recommend!",
      textMl:
        "എന്റെ മകൾക്ക് അടിയന്തിരമായി ഒരു മാത്തമാറ്റിക്സ് ട്യൂട്ടർ ആവശ്യമായിരുന്നു. മിനിറ്റുകൾക്കുള്ളിൽ ഗിഗ്‌വർക്ക് എന്നെ എന്റെ അയൽപക്കത്തെ ഒരു യോഗ്യതയുള്ള അധ്യാപകനുമായി ബന്ധിപ്പിച്ചു. ശക്തമായി ശുപാർശ ചെയ്യുന്നു!",
      rating: 5,
    },
    {
      name: "Anoop Krishnan",
      location: "Calicut",
      text: "Used Gigwork to find a plumber on a Sunday. Not only did they respond quickly, but the service was professional and affordable. This app is a game-changer!",
      textMl:
        "ഞായറാഴ്ച ഒരു പ്ലംബറെ കണ്ടെത്താൻ ഗിഗ്‌വർക്ക് ഉപയോഗിച്ചു. അവർ വേഗത്തിൽ പ്രതികരിച്ചു മാത്രമല്ല, സേവനം പ്രൊഫഷണലും താങ്ങാനാവുന്നതുമായിരുന്നു. ഈ ആപ്പ് ഒരു ഗെയിം ചേഞ്ചർ ആണ്!",
      rating: 4,
    },
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 5000); // Change slide every 5 seconds

    return () => clearInterval(interval);
  }, [testimonials.length]);

  // Helper function to render category icon
  const renderCategoryIcon = (iconName: string) => {
    switch (iconName) {
      case "home":
        return <Home className="h-6 w-6 text-green-600" />;
      case "book":
        return <Book className="h-6 w-6 text-green-600" />;
      case "tool":
        return <Tool className="h-6 w-6 text-green-600" />;
      case "hammer":
        return <Hammer className="h-6 w-6 text-green-600" />;
      case "briefcase":
        return <Briefcase className="h-6 w-6 text-green-600" />;
      case "calendar":
        return <Calendar className="h-6 w-6 text-green-600" />;
      case "heart":
        return <Heart className="h-6 w-6 text-green-600" />;
      case "users":
        return <Users className="h-6 w-6 text-green-600" />;
      case "truck":
        return <Truck className="h-6 w-6 text-green-600" />;
      case "car":
        return <Car className="h-6 w-6 text-green-600" />; // Add this case
      case "cross":
        return <Cross className="h-6 w-6 text-green-600" />;
      case "map":
        return <MapPin className="h-6 w-6 text-green-600" />;
      case "message":
        return <MessageCircle className="h-6 w-6 text-green-600" />;
      case "mail":
        return <Mail className="h-6 w-6 text-green-600" />;
      case "shopping":
        return (
          <svg
            className="h-6 w-6 text-green-600"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <circle cx="9" cy="21" r="1" />
            <circle cx="20" cy="21" r="1" />
            <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
          </svg>
        );
      default:
        return <Home className="h-6 w-6 text-green-600" />;
    }
  };
  const whatsapp = () => {
    window.open("https://wa.me/+918590012027", "_blank");
  };

  // Helper function to render step icon
  const renderStepIcon = (iconName: string) => {
    switch (iconName) {
      case "search":
        return <Search className="h-10 w-10 text-green-600" />;
      case "message":
        return <MessageCircle className="h-10 w-10 text-green-600" />;
      case "users":
        return <Users className="h-10 w-10 text-green-600" />;
      default:
        return <Search className="h-10 w-10 text-green-600" />;
    }
  };
  // Add this function to map category titles to appropriate icon keys
  // Update your getCategoryIcon function to handle specific category names
  const getCategoryIcon = (categoryTitle: string): string => {
    const title = categoryTitle.toLowerCase();

    if (title.includes("farming") || title.includes("agri")) return "home";
    if (title.includes("government") || title.includes("ngo")) return "users";
    if (title.includes("money") || title.includes("legal")) return "briefcase";
    if (title.includes("vehicle") || title.includes("dealership")) return "car"; // Use car icon
    if (title.includes("business") || title.includes("office")) return "calendar";
    if (title.includes("construction") || title.includes("property")) return "hammer";
    if (title.includes("digital") || title.includes("creative")) return "tool";
    if (title.includes("education") || title.includes("training")) return "book";
    if (title.includes("food") || title.includes("hospitality")) return "heart";
    if (title.includes("health") || title.includes("wellness")) return "cross";
    if (title.includes("home") || title.includes("handy")) return "map";
    if (title.includes("manufacturing") || title.includes("production")) return "hammer"; // Hammer for manufacturing
    if (title.includes("media") || title.includes("entertainment")) return "message";
    if (title.includes("miscellaneous")) return "mail";
    if (title.includes("sales") || title.includes("retail")) return "shopping";
    if (title.includes("technology") || title.includes("innovation")) return "tool";
    if (title.includes("transport") || title.includes("moving")) return "truck";

    // Default icon
    return "home";
  };
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white shadow-sm">
        <div className="container mx-auto px-4 py-3 flex justify-between items-center">
          <a href="/" className="flex items-center">
            <Image
              src={gigworks}
              alt="GigWork Logo"
              width={40}
              height={40}
              className="w-28 md:w-40"
            />
          </a>
          <div className=" space-x-4">
            {/* <button
              onClick={toggleLanguage}
              className="text-sm font-medium text-gray-600 hover:text-green-600"
            >
              {language === "en" ? "മലയാളം" : "English"}
            </button> */}
            <button onClick={whatsapp} className="inline-flex items-center justify-center hidden md:flex px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition">
              {/* Simplified WhatsApp SVG */}
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="mr-2 flex-shrink-0"
              >
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
              </svg>
              Chat
            </button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="bg-gradient-to-b from-green-50 to-white py-12 md:py-20">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-800 mb-6">
            {translations.heroTitle}
          </h1>
          <p className="text-lg md:text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            {translations.heroSubtitle}
          </p>

          {/* Replace the old search bar with the new component */}
          <div className="max-w-3xl mx-auto mb-12">
            <ServiceSearchSection />
          </div>

          {/* WhatsApp Button (Mobile) */}
          <div className="md:hidden">
            <a
              href="https://wa.me/+918590012027"
              className="inline-flex items-center px-5 py-3 bg-green-600 text-white rounded-full hover:bg-green-700 transition shadow-md"
            >
              <MessageCircle className="h-5 w-5 mr-2" />
              {translations.whatsappCTA}
            </a>
          </div>
        </div>
      </section>

      {/* Categories Section - Original UI with dynamic data */}
      <section className="py-12 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {translations.categoriesTitle}
          </h2>

          {isLoadingCategories ? (
            <CategorySkeleton />
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 max-w-4xl mx-auto">
              {fetchedCategories.map((category, index) => (
                <Link
                  href={`/category/${category.id}`}
                  key={index}
                  className="flex flex-col items-center space-y-4 bg-white p-6 rounded-lg shadow-sm hover:shadow-md transition"
                >
                  <div className="bg-green-50 p-4 rounded-full">
                    {renderCategoryIcon(getCategoryIcon(category.title))}
                  </div>
                  <span className="text-center font-medium text-gray-800">
                    {language === "en" ? category.title : category.title}{" "}
                    {/* Replace with ML version if available */}
                  </span>
                </Link>
              ))}
            </div>
          )}

          {!isLoadingCategories && fetchedCategories.length === 0 && (
            <div className="text-center text-gray-500 mt-8">
              No categories available
            </div>
          )}
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-12 bg-gray-50">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {translations.testimonialsTitle}
          </h2>

          <div className="max-w-2xl mx-auto relative">
            {/* Current Testimonial */}
            <div className="bg-white rounded-lg shadow-md p-6 border-l-4 border-green-500 transition-all duration-300">
              <div className="flex items-start mb-4">
                <div className="bg-gray-200 rounded-full w-12 h-12 flex items-center justify-center mr-4">
                  <Users className="h-6 w-6 text-gray-500" />
                </div>
                <div>
                  <h3 className="font-bold text-gray-800">
                    {testimonials[currentTestimonial].name}
                  </h3>
                  <p className="text-sm text-gray-500">
                    {testimonials[currentTestimonial].location}
                  </p>
                </div>
              </div>
              <p className="text-gray-600 italic min-h-[100px]">
                {language === "en"
                  ? testimonials[currentTestimonial].text
                  : testimonials[currentTestimonial].textMl}
              </p>
              <div className="mt-3 flex">
                {[1, 2, 3, 4, 5].map((star) => (
                  <svg
                    key={star}
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    fill={
                      star <= testimonials[currentTestimonial].rating
                        ? "currentColor"
                        : "none"
                    }
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className={`h-5 w-5 ${
                      star <= testimonials[currentTestimonial].rating
                        ? "text-yellow-400"
                        : "text-gray-300"
                    }`}
                  >
                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                  </svg>
                ))}
              </div>
            </div>

            {/* Navigation Buttons */}
            {/* <button
              onClick={() =>
                setCurrentTestimonial((prev) =>
                  prev === 0 ? testimonials.length - 1 : prev - 1
                )
              }
              className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-12 bg-white rounded-full p-2 shadow-md text-green-600 hover:text-green-700 focus:outline-none"
              aria-label="Previous testimonial"
            >
              <ChevronLeft className="h-6 w-6" />
            </button>

            <button
              onClick={() =>
                setCurrentTestimonial(
                  (prev) => (prev + 1) % testimonials.length
                )
              }
              className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-12 bg-white rounded-full p-2 shadow-md text-green-600 hover:text-green-700 focus:outline-none"
              aria-label="Next testimonial"
            >
              <ChevronRight className="h-6 w-6" />
            </button> */}

            {/* Indicator Dots */}
            <div className="flex justify-center space-x-2 mt-6">
              {testimonials.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentTestimonial(index)}
                  className={`w-3 h-3 rounded-full ${
                    currentTestimonial === index
                      ? "bg-green-600"
                      : "bg-gray-300"
                  }`}
                  aria-label={`Go to testimonial ${index + 1}`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-12 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {translations.howItWorksTitle}
          </h2>

          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {steps.map((step, index) => (
              <div
                key={index}
                className="bg-white rounded-lg shadow-md p-6 text-center relative"
              >
                <div className="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-green-600 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold">
                  {index + 1}
                </div>
                <div className="mb-4 flex justify-center">
                  {renderStepIcon(step.icon)}
                </div>
                <h3 className="font-bold text-lg mb-2 text-gray-800">
                  {language === "en" ? step.title : step.titleMl}
                </h3>
                <p className="text-gray-600">
                  {language === "en" ? step.description : step.descriptionMl}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-12 bg-green-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-2xl md:text-3xl font-bold mb-6">
            {translations.ctaTitle}
          </h2>
          <p className="text-lg mb-8 max-w-2xl mx-auto opacity-90">
            {translations.ctaSubtitle}
          </p>
          <a
            href="https://wa.me/+918590012027"
            className="inline-flex items-center px-6 py-3 bg-white text-green-600 rounded-full hover:bg-gray-100 transition shadow-md font-medium"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              x="0px"
              y="0px"
              width="20"
              className="mr-2"
              height="20"
              viewBox="0,0,256,256"
            >
              <g
                fill="currentColor"
                fill-rule="nonzero"
                stroke="none"
                stroke-width="1"
                stroke-linecap="butt"
                stroke-linejoin="miter"
                stroke-miterlimit="10"
                stroke-dasharray=""
                stroke-dashoffset="0"
                font-family="none"
                font-weight="none"
                font-size="none"
                text-anchor="none"
                style={{ mixBlendMode: "normal" }}
              >
                <g transform="scale(10.66667,10.66667)">
                  <path d="M12.01172,2c-5.506,0 -9.98823,4.47838 -9.99023,9.98438c-0.001,1.76 0.45998,3.47819 1.33398,4.99219l-1.35547,5.02344l5.23242,-1.23633c1.459,0.796 3.10144,1.21384 4.77344,1.21484h0.00391c5.505,0 9.98528,-4.47937 9.98828,-9.98437c0.002,-2.669 -1.03588,-5.17841 -2.92187,-7.06641c-1.886,-1.887 -4.39245,-2.92673 -7.06445,-2.92773zM12.00977,4c2.136,0.001 4.14334,0.8338 5.65234,2.3418c1.509,1.51 2.33794,3.51639 2.33594,5.65039c-0.002,4.404 -3.58423,7.98633 -7.99023,7.98633c-1.333,-0.001 -2.65341,-0.3357 -3.81641,-0.9707l-0.67383,-0.36719l-0.74414,0.17578l-1.96875,0.46484l0.48047,-1.78516l0.2168,-0.80078l-0.41406,-0.71875c-0.698,-1.208 -1.06741,-2.58919 -1.06641,-3.99219c0.002,-4.402 3.58528,-7.98437 7.98828,-7.98437zM8.47656,7.375c-0.167,0 -0.43702,0.0625 -0.66602,0.3125c-0.229,0.249 -0.875,0.85208 -0.875,2.08008c0,1.228 0.89453,2.41503 1.01953,2.58203c0.124,0.166 1.72667,2.76563 4.26367,3.76563c2.108,0.831 2.53614,0.667 2.99414,0.625c0.458,-0.041 1.47755,-0.60255 1.68555,-1.18555c0.208,-0.583 0.20848,-1.0845 0.14648,-1.1875c-0.062,-0.104 -0.22852,-0.16602 -0.47852,-0.29102c-0.249,-0.125 -1.47608,-0.72755 -1.70508,-0.81055c-0.229,-0.083 -0.3965,-0.125 -0.5625,0.125c-0.166,0.25 -0.64306,0.81056 -0.78906,0.97656c-0.146,0.167 -0.29102,0.18945 -0.54102,0.06445c-0.25,-0.126 -1.05381,-0.39024 -2.00781,-1.24024c-0.742,-0.661 -1.24267,-1.47656 -1.38867,-1.72656c-0.145,-0.249 -0.01367,-0.38577 0.11133,-0.50977c0.112,-0.112 0.24805,-0.2915 0.37305,-0.4375c0.124,-0.146 0.167,-0.25002 0.25,-0.41602c0.083,-0.166 0.04051,-0.3125 -0.02149,-0.4375c-0.062,-0.125 -0.54753,-1.35756 -0.76953,-1.85156c-0.187,-0.415 -0.3845,-0.42464 -0.5625,-0.43164c-0.145,-0.006 -0.31056,-0.00586 -0.47656,-0.00586z"></path>
                </g>
              </g>
            </svg>
            {translations.startWhatsapp}
          </a>
        </div>
      </section>

      {/* Footer */}
      <FooterSection></FooterSection>

      {/* Fixed WhatsApp Button */}
      <a
        href="https://wa.me/+918590012027"
        className="fixed bottom-[3rem] sm:bottom-6 right-6 bg-green-600 text-white p-4 rounded-full shadow-lg hover:bg-green-700 transition z-50 flex items-center justify-center"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          x="0px"
          y="0px"
          width="20"
          height="20"
          viewBox="0,0,256,256"
        >
          <g
            fill="currentColor"
            fill-rule="nonzero"
            stroke="none"
            stroke-width="1"
            stroke-linecap="butt"
            stroke-linejoin="miter"
            stroke-miterlimit="10"
            stroke-dasharray=""
            stroke-dashoffset="0"
            font-family="none"
            font-weight="none"
            font-size="none"
            text-anchor="none"
            style={{ mixBlendMode: "normal" }}
          >
            <g transform="scale(10.66667,10.66667)">
              <path d="M12.01172,2c-5.506,0 -9.98823,4.47838 -9.99023,9.98438c-0.001,1.76 0.45998,3.47819 1.33398,4.99219l-1.35547,5.02344l5.23242,-1.23633c1.459,0.796 3.10144,1.21384 4.77344,1.21484h0.00391c5.505,0 9.98528,-4.47937 9.98828,-9.98437c0.002,-2.669 -1.03588,-5.17841 -2.92187,-7.06641c-1.886,-1.887 -4.39245,-2.92673 -7.06445,-2.92773zM12.00977,4c2.136,0.001 4.14334,0.8338 5.65234,2.3418c1.509,1.51 2.33794,3.51639 2.33594,5.65039c-0.002,4.404 -3.58423,7.98633 -7.99023,7.98633c-1.333,-0.001 -2.65341,-0.3357 -3.81641,-0.9707l-0.67383,-0.36719l-0.74414,0.17578l-1.96875,0.46484l0.48047,-1.78516l0.2168,-0.80078l-0.41406,-0.71875c-0.698,-1.208 -1.06741,-2.58919 -1.06641,-3.99219c0.002,-4.402 3.58528,-7.98437 7.98828,-7.98437zM8.47656,7.375c-0.167,0 -0.43702,0.0625 -0.66602,0.3125c-0.229,0.249 -0.875,0.85208 -0.875,2.08008c0,1.228 0.89453,2.41503 1.01953,2.58203c0.124,0.166 1.72667,2.76563 4.26367,3.76563c2.108,0.831 2.53614,0.667 2.99414,0.625c0.458,-0.041 1.47755,-0.60255 1.68555,-1.18555c0.208,-0.583 0.20848,-1.0845 0.14648,-1.1875c-0.062,-0.104 -0.22852,-0.16602 -0.47852,-0.29102c-0.249,-0.125 -1.47608,-0.72755 -1.70508,-0.81055c-0.229,-0.083 -0.3965,-0.125 -0.5625,0.125c-0.166,0.25 -0.64306,0.81056 -0.78906,0.97656c-0.146,0.167 -0.29102,0.18945 -0.54102,0.06445c-0.25,-0.126 -1.05381,-0.39024 -2.00781,-1.24024c-0.742,-0.661 -1.24267,-1.47656 -1.38867,-1.72656c-0.145,-0.249 -0.01367,-0.38577 0.11133,-0.50977c0.112,-0.112 0.24805,-0.2915 0.37305,-0.4375c0.124,-0.146 0.167,-0.25002 0.25,-0.41602c0.083,-0.166 0.04051,-0.3125 -0.02149,-0.4375c-0.062,-0.125 -0.54753,-1.35756 -0.76953,-1.85156c-0.187,-0.415 -0.3845,-0.42464 -0.5625,-0.43164c-0.145,-0.006 -0.31056,-0.00586 -0.47656,-0.00586z"></path>
            </g>
          </g>
        </svg>
      </a>
    </div>
  );
}

// admin/src/views/service.vue
<template>
    <div class="min-h-screen bg-white">
      <!-- Header -->
      <header class="sticky top-0 z-50 bg-white shadow-sm">
        <div class="container mx-auto px-4 py-3 flex justify-between items-center">
          <div class="flex items-center">
            <div class="text-2xl font-bold text-green-600">Gigwork</div>
          </div>
          <div class="flex items-center space-x-4">
            <button @click="toggleLanguage" class="text-sm font-medium text-gray-600 hover:text-green-600">
              {{ language === 'en' ? 'മലയാളം' : 'English' }}
            </button>
            <button class="hidden md:block px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition">
              {{ translations.signIn }}
            </button>
          </div>
        </div>
      </header>
  
      <!-- Hero Section -->
      <section class="bg-gradient-to-b from-green-50 to-white py-12 md:py-20">
        <div class="container mx-auto px-4 text-center">
          <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-800 mb-6">
            {{ translations.heroTitle }}
          </h1>
          <p class="text-lg md:text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            {{ translations.heroSubtitle }}
          </p>
          
          <!-- Search Bar -->
          <div class="relative max-w-md mx-auto mb-12">
            <input 
              type="text" 
              :placeholder="translations.searchPlaceholder" 
              class="w-full px-5 py-3 rounded-full border border-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent shadow-sm"
            />
            <button class="absolute right-2 top-1/2 transform -translate-y-1/2 bg-green-600 text-white p-2 rounded-full hover:bg-green-700 transition">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
                <circle cx="11" cy="11" r="8"></circle>
                <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
              </svg>
            </button>
          </div>
          
          <!-- WhatsApp Button (Mobile) -->
          <div class="md:hidden">
            <a href="https://wa.me/+919876543210" class="inline-flex items-center px-5 py-3 bg-green-600 text-white rounded-full hover:bg-green-700 transition shadow-md">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>
              </svg>
              {{ translations.whatsappCTA }}
            </a>
          </div>
        </div>
      </section>
  
      <!-- Categories Section -->
      <section class="py-12 bg-white">
        <div class="container mx-auto px-4">
          <h2 class="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {{ translations.categoriesTitle }}
          </h2>
          
          <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div v-for="(category, index) in categories" :key="index" class="bg-white rounded-lg shadow-md hover:shadow-lg transition p-4 text-center cursor-pointer">
              <div class="bg-green-100 p-4 rounded-full inline-flex items-center justify-center mb-3">
                <template v-if="category.icon === 'home'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'book'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path>
                    <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'tool'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'briefcase'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect>
                    <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'calendar'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                    <line x1="16" y1="2" x2="16" y2="6"></line>
                    <line x1="8" y1="2" x2="8" y2="6"></line>
                    <line x1="3" y1="10" x2="21" y2="10"></line>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'heart'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'users'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                  </svg>
                </template>
                <template v-else-if="category.icon === 'truck'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-green-600">
                    <rect x="1" y="3" width="15" height="13"></rect>
                    <polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon>
                    <circle cx="5.5" cy="18.5" r="2.5"></circle>
                    <circle cx="18.5" cy="18.5" r="2.5"></circle>
                  </svg>
                </template>
              </div>
              <h3 class="font-medium text-gray-800">{{ language === 'en' ? category.name : category.nameMl }}</h3>
            </div>
          </div>
        </div>
      </section>
  
      <!-- How It Works Section -->
      <section class="py-12 bg-gray-50">
        <div class="container mx-auto px-4">
          <h2 class="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {{ translations.howItWorksTitle }}
          </h2>
          
          <div class="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div v-for="(step, index) in steps" :key="index" class="bg-white rounded-lg shadow-md p-6 text-center relative">
              <div class="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-green-600 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold">
                {{ index + 1 }}
              </div>
              <div class="mb-4 flex justify-center">
                <template v-if="step.icon === 'search'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-10 w-10 text-green-600">
                    <circle cx="11" cy="11" r="8"></circle>
                    <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                  </svg>
                </template>
                <template v-else-if="step.icon === 'message'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-10 w-10 text-green-600">
                    <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>
                  </svg>
                </template>
                <template v-else-if="step.icon === 'users'">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-10 w-10 text-green-600">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                  </svg>
                </template>
              </div>
              <h3 class="font-bold text-lg mb-2 text-gray-800">{{ language === 'en' ? step.title : step.titleMl }}</h3>
              <p class="text-gray-600">{{ language === 'en' ? step.description : step.descriptionMl }}</p>
            </div>
          </div>
        </div>
      </section>
  
      <!-- Testimonials Section -->
      <section class="py-12 bg-white">
        <div class="container mx-auto px-4">
          <h2 class="text-2xl md:text-3xl font-bold text-center text-gray-800 mb-10">
            {{ translations.testimonialsTitle }}
          </h2>
          
          <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <div v-for="(testimonial, index) in testimonials" :key="index" class="bg-white rounded-lg shadow-md p-6 border-l-4 border-green-500">
              <div class="flex items-start mb-4">
                <div class="bg-gray-200 rounded-full w-12 h-12 flex items-center justify-center mr-4">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6 text-gray-500">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div>
                  <h3 class="font-bold text-gray-800">{{ testimonial.name }}</h3>
                  <p class="text-sm text-gray-500">{{ testimonial.location }}</p>
                </div>
              </div>
              <p class="text-gray-600 italic">{{ language === 'en' ? testimonial.text : testimonial.textMl }}</p>
              <div class="mt-3 flex">
                <template v-for="i in 5" :key="i">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5" :class="i <= testimonial.rating ? 'text-yellow-400' : 'text-gray-300'">
                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                  </svg>
                </template>
              </div>
            </div>
          </div>
        </div>
      </section>
  
      <!-- CTA Section -->
      <section class="py-12 bg-green-600 text-white">
        <div class="container mx-auto px-4 text-center">
          <h2 class="text-2xl md:text-3xl font-bold mb-6">{{ translations.ctaTitle }}</h2>
          <p class="text-lg mb-8 max-w-2xl mx-auto opacity-90">{{ translations.ctaSubtitle }}</p>
          <a href="https://wa.me/+919876543210" class="inline-flex items-center px-6 py-3 bg-white text-green-600 rounded-full hover:bg-gray-100 transition shadow-md font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
              <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>
            </svg>
            {{ translations.startWhatsapp }}
          </a>
        </div>
      </section>
  
      <!-- Footer -->
      <footer class="bg-gray-800 text-white py-10">
        <div class="container mx-auto px-4">
          <div class="grid md:grid-cols-3 gap-8">
            <div>
              <h3 class="text-xl font-bold mb-4">Gigwork</h3>
              <p class="text-gray-400">{{ translations.footerTagline }}</p>
            </div>
            <div>
              <h3 class="text-lg font-bold mb-4">{{ translations.quickLinks }}</h3>
              <ul class="space-y-2">
                <li><a href="#" class="text-gray-400 hover:text-white transition">{{ translations.aboutUs }}</a></li>
                <li><a href="#" class="text-gray-400 hover:text-white transition">{{ translations.services }}</a></li>
                <li><a href="#" class="text-gray-400 hover:text-white transition">{{ translations.contactUs }}</a></li>
              </ul>
            </div>
            <div>
              <h3 class="text-lg font-bold mb-4">{{ translations.contact }}</h3>
              <ul class="space-y-2 text-gray-400">
                <li class="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                    <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
                    <circle cx="12" cy="10" r="3"></circle>
                  </svg>
                  Kochi, Kerala, India
                </li>
                <li class="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                    <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
                  </svg>
                  +91 9876 543 210
                </li>
                <li class="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                    <polyline points="22,6 12,13 2,6"></polyline>
                  </svg>
                  info@gigwork.in
                </li>
              </ul>
            </div>
          </div>
          <div class="border-t border-gray-700 mt-8 pt-8 text-center text-gray-400">
            <p>&copy; 2025 Gigwork. {{ translations.allRightsReserved }}</p>
          </div>
        </div>
      </footer>
  
      <!-- Fixed WhatsApp Button -->
      <a href="https://wa.me/+919876543210" class="fixed bottom-6 right-6 bg-green-600 text-white p-4 rounded-full shadow-lg hover:bg-green-700 transition z-50 flex items-center justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-6 w-6">
          <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>
        </svg>
      </a>
    </div>
  </template>
  
  <script setup>
  import { ref, computed } from 'vue';
  
  const language = ref('en');
  
  const toggleLanguage = () => {
    language.value = language.value === 'en' ? 'ml' : 'en';
  };
  
  const translations = computed(() => {
    return {
      // Translations based on current language
      heroTitle: language.value === 'en' ? 'Find Trusted Experts Near You' : 'നിങ്ങൾക്ക് അടുത്തുള്ള വിശ്വസനീയരായ വിദഗ്ധരെ കണ്ടെത്തുക',
      heroSubtitle: language.value === 'en' ? 'Connect with skilled professionals in Kerala via WhatsApp for all your service needs' : 'നിങ്ങളുടെ എല്ലാ സേവന ആവശ്യങ്ങൾക്കും വാട്സ്ആപ്പ് വഴി കേരളത്തിലെ വിദഗ്ധ പ്രൊഫഷണലുകളുമായി ബന്ധപ്പെടുക',
      searchPlaceholder: language.value === 'en' ? 'Search for a service...' : 'ഒരു സേവനം തിരയുക...',
      whatsappCTA: language.value === 'en' ? 'Chat on WhatsApp' : 'വാട്സ്ആപ്പിൽ ചാറ്റ് ചെയ്യുക',
      categoriesTitle: language.value === 'en' ? 'Browse Services by Category' : 'വിഭാഗം അനുസരിച്ച് സേവനങ്ങൾ ബ്രൗസ് ചെയ്യുക',
      howItWorksTitle: language.value === 'en' ? 'How It Works' : 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
      testimonialsTitle: language.value === 'en' ? 'What Our Users Say' : 'ഞങ്ങളുടെ ഉപയോക്താക്കൾ പറയുന്നത്',
      ctaTitle: language.value === 'en' ? 'Ready to Find Your Service Provider?' : 'നിങ്ങളുടെ സേവന ദാതാവിനെ കണ്ടെത്താൻ തയ്യാറാണോ?',
      ctaSubtitle: language.value === 'en' ? 'Start a conversation on WhatsApp and get connected with the best professionals in Kerala' : 'വാട്സ്ആപ്പിൽ ഒരു സംഭാഷണം ആരംഭിക്കുകയും കേരളത്തിലെ മികച്ച പ്രൊഫഷണലുകളുമായി ബന്ധപ്പെടുകയും ചെയ്യുക',
      startWhatsapp: language.value === 'en' ? 'Start on WhatsApp' : 'വാട്സ്ആപ്പിൽ ആരംഭിക്കുക',
      footerTagline: language.value === 'en' ? 'Connecting Kerala with trusted local service providers' : 'കേരളത്തെ വിശ്വസനീയമായ പ്രാദേശിക സേവന ദാതാക്കളുമായി ബന്ധിപ്പിക്കുന്നു',
      quickLinks: language.value === 'en' ? 'Quick Links' : 'ക്വിക്ക് ലിങ്കുകൾ',
      aboutUs: language.value === 'en' ? 'About Us' : 'ഞങ്ങളെക്കുറിച്ച്',
      services: language.value === 'en' ? 'Services' : 'സേവനങ്ങൾ',
      contactUs: language.value === 'en' ? 'Contact Us' : 'ഞങ്ങളെ സമീപിക്കുക',
      contact: language.value === 'en' ? 'Contact' : 'ബന്ധപ്പെടുക',
      allRightsReserved: language.value === 'en' ? 'All Rights Reserved' : 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം',
      signIn: language.value === 'en' ? 'Sign In' : 'സൈൻ ഇൻ',
    };
  });
  
  const categories = [
    { 
      name: 'Home Services', 
      nameMl: 'ഹോം സർവീസസ്',
      icon: 'home' 
    },
    { 
      name: 'Education', 
      nameMl: 'വിദ്യാഭ്യാസം',
      icon: 'book' 
    },
    { 
      name: 'Repairs', 
      nameMl: 'റിപ്പയറുകൾ',
      icon: 'tool' 
    },
    { 
      name: 'Professional', 
      nameMl: 'പ്രൊഫഷണൽ',
      icon: 'briefcase' 
    },
    { 
      name: 'Events', 
      nameMl: 'ഇവന്റുകൾ',
      icon: 'calendar' 
    },
    { 
      name: 'Healthcare', 
      nameMl: 'ആരോഗ്യ പരിരക്ഷ',
      icon: 'heart' 
    },
    { 
      name: 'Beauty', 
      nameMl: 'സൗന്ദര്യം',
      icon: 'users' 
    },
    { 
      name: 'Delivery', 
      nameMl: 'ഡെലിവറി',
      icon: 'truck' 
    }
  ];
  
  const steps = [
    {
      title: 'Search or Choose a Category',
      titleMl: 'തിരയുക അല്ലെങ്കിൽ ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക',
      description: 'Find the service you need from our wide range of categories',
      descriptionMl: 'ഞങ്ങളുടെ വിപുലമായ വിഭാഗങ്ങളിൽ നിന്ന് നിങ്ങൾക്ക് ആവശ്യമായ സേവനം കണ്ടെത്തുക',
      icon: 'search'
    },
    {
      title: 'Chat on WhatsApp',
      titleMl: 'വാട്സ്ആപ്പിൽ ചാറ്റ് ചെയ്യുക',
      description: 'Connect directly with service providers via WhatsApp',
      descriptionMl: 'വാട്സ്ആപ്പ് വഴി സേവന ദാതാക്കളുമായി നേരിട്ട് ബന്ധപ്പെടുക',
      icon: 'message'
    },
    {
      title: 'Get the Service',
      titleMl: 'സേവനം നേടുക',
      description: 'Receive quality service from trusted local professionals',
      descriptionMl: 'വിശ്വസനീയമായ പ്രാദേശിക പ്രൊഫഷണലുകളിൽ നിന്ന് ഗുണനിലവാരമുള്ള സേവനം ലഭിക്കുക',
      icon: 'users'
    }
  ];
  
  const testimonials = [
    {
      name: 'Priya Thomas',
      location: 'Kochi',
      text: 'Found an excellent electrician through Gigwork. He fixed all the issues in my new apartment within hours. The WhatsApp connection made it so easy!',
      textMl: 'ഗിഗ്‌വർക്ക് വഴി ഒരു മികച്ച ഇലക്ട്രീഷ്യനെ കണ്ടെത്തി. എന്റെ പുതിയ അപ്പാർട്ട്മെന്റിലെ എല്ലാ പ്രശ്നങ്ങളും അദ്ദേഹം മണിക്കൂറുകൾക്കുള്ളിൽ പരിഹരിച്ചു. വാട്സ്ആപ്പ് കണക്ഷൻ അത് വളരെ എളുപ്പമാക്കി!',
      rating: 5
    },
    {
      name: 'Rahul Menon',
      location: 'Trivandrum',
      text: 'Needed a math tutor for my daughter urgently. Gigwork connected me with a qualified teacher in my neighborhood within minutes. Highly recommend!',
      textMl: 'എന്റെ മകൾക്ക് അടിയന്തിരമായി ഒരു മാത്തമാറ്റിക്സ് ട്യൂട്ടർ ആവശ്യമായിരുന്നു. മിനിറ്റുകൾക്കുള്ളിൽ ഗിഗ്‌വർക്ക് എന്നെ എന്റെ അയൽപക്കത്തെ ഒരു യോഗ്യതയുള്ള അധ്യാപകനുമായി ബന്ധിപ്പിച്ചു. ശക്തമായി ശുപാർശ ചെയ്യുന്നു!',
      rating: 5
    },
    {
      name: 'Anoop Krishnan',
      location: 'Calicut',
      text: 'Used Gigwork to find a plumber on a Sunday. Not only did they respond quickly, but the service was professional and affordable. This app is a game-changer!',
      textMl: 'ഞായറാഴ്ച ഒരു പ്ലംബറെ കണ്ടെത്താൻ ഗിഗ്‌വർക്ക് ഉപയോഗിച്ചു. അവർ വേഗത്തിൽ പ്രതികരിച്ചു മാത്രമല്ല, സേവനം പ്രൊഫഷണലും താങ്ങാനാവുന്നതുമായിരുന്നു. ഈ ആപ്പ് ഒരു ഗെയിം ചേഞ്ചർ ആണ്!',
      rating: 4
    }
  ];
  </script>
  
  <style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  
  :root {
    --primary: #25D366;
    --primary-dark: #128C7E;
    --secondary: #34B7F1;
    --text-dark: #333333;
    --text-light: #666666;
  }
  
  body {
    font-family: 'Inter', sans-serif;
    color: var(--text-dark);
  }
  
  .bg-green-600 {
    background-color: var(--primary);
  }
  
  .bg-green-700 {
    background-color: var(--primary-dark);
  }
  
  .text-green-600 {
    color: var(--primary);
  }
  
  .border-green-500 {
    border-color: var(--primary);
  }
  
  .bg-green-100 {
    background-color: rgba(37, 211, 102, 0.1);
  }
  
  .bg-green-50 {
    background-color: rgba(37, 211, 102, 0.05);
  }
  </style>
